
# Types of placeholders
__TYPE_BODY = 2
__TYPE_TITLE = 1
__TYPE_PICTURE = 18
__TYPE_OBJECT = 7

__COMMON_IMAGE = [__TYPE_PICTURE]
__COMMON_TEXT = [__TYPE_OBJECT, __TYPE_BODY, __TYPE_TITLE]

'''
All below placeholders have firstly their identify text as
the first object and secondly an array of placeholder-types that the placeholder must be an instance of
'''

MEMBER_1 = ("M1", __COMMON_TEXT)
MEMBER_2 = ("M2", __COMMON_TEXT)
MEMBER_3 = ("M3", __COMMON_TEXT)
SCHOOL = ("Location", __COMMON_TEXT)

PROJECT_IMAGE = ("PJI", __COMMON_IMAGE)

PROJECT_TITLE = ("Title", __COMMON_TEXT)

NOTES = ("Notes", __COMMON_TEXT)

LOOKUP_PRICE_1 = ("P1", __COMMON_IMAGE)
LOOKUP_PRICE_2 = ("P2", __COMMON_IMAGE)

# P1IR - Price 1 Image Rotating
# P2TE - Price 2 Text Flyin
PROJECT_PRICES_1_FLYIN_TEXT = ("P1TF", __COMMON_TEXT)
PROJECT_PRICES_1_FLYIN_IMAGE = ("P1IF", __COMMON_IMAGE)
PROJECT_PRICES_2_FLYIN_TEXT = ("P2TF", __COMMON_TEXT)
PROJECT_PRICES_2_FLYIN_IMAGE = ("P2IF", __COMMON_IMAGE)
PROJECT_PRICES_1_ROTATING_TEXT = ("P1TR", __COMMON_TEXT)
PROJECT_PRICES_1_ROTATING_IMAGE = ("P1IR", __COMMON_IMAGE)
PROJECT_PRICES_2_ROTATING_TEXT = ("P2TR", __COMMON_TEXT)
PROJECT_PRICES_2_ROTATING_IMAGE = ("P2IR", __COMMON_IMAGE)
